version: '3'

services:
    db:
        image: mariadb
        restart: unless-stopped
        env_file: .env
        volumes:
            - ./db/config:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE=$MYSQL_DATABASE
            - MYSQL_USER=$MYSQL_USER
            - MYSQL_PASSWORD=$MYSQL_PASSWORD
#        ports:
#            - 3307:3306
        networks:
            - wp-network
    web:
        image: wordpress
        depends_on:
            - db
        restart: unless-stopped
        env_file: .env
        volumes:
            - ./wordpress/html:/var/www/html
            - ./wordpress/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        environment:
            - WORDPRESS_DB_USER=$MYSQL_USER
            - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
            - WORDPRESS_DB_HOST=db
        ports:
            - 8080:80
        networks:
            - wp-network